### ISSUE TITLE
duplicate entries

### ISSUE THREAD

**Issue by pennyl67** [liderproject/linghub#11]
At the browsing pages, I notice that entries from MetaShare appear twice, one with the link to the MetaShare record and one with the resource title; I don't know if this happens for all or for a subset.
E.g.
http://linghub.lider-project.eu/metashare/49b5d6ee6b0011e284b6000423bfd61c376f72c09111449181f010b89704ee07
and 
LFG Treebank for Polish with the same link as above

**Comment by pennyl67** [comment]
I noticed that actually they appear more than twice. Search for "Greek Dependency Treebank" and out of the 5 search results, three records are the same.

**Comment by jmccrae** [comment]
Already fixed, but not pushed to production yet
