### ISSUE TITLE
display of metashare elements

### ISSUE THREAD

**Issue by pennyl67** [liderproject/linghub#13]
1) At MetaShare the ...Info components are used for grouping together elements; in case there are multiple components, the elements inside each component are semantically linked and should remain as such. At linghub all these are mixed together. 
For instance, if you look at: http://linghub.lider-project.eu/metashare/3fe5648844c511e2bc64842b2b6a04d7d113db381571424baff332c496620250
 the annotationInfo box displays all the elements mixed. If you have a look at the original metashare record http://metashare.elda.org/repository/browse/greek-dependency-treebank/3fe5648844c511e2bc64842b2b6a04d7d113db381571424baff332c496620250/, you can see that each annotationInfo groups together different information: e.g. each annotationType has been performed by different tools, annotation mode and annotators etc.
2) If possible, keep the sorting of elements as they are in the MetaShare XSD instead of an alphabetical sorting; they are more user-friendly and informative as in the XSD.

**Comment by jmccrae** [comment]
Hi the first point is the same #14, the second point is due to the nature of RDF, keeping the XSD order would involve adding too much extra data so I would prefer to avoid it, although if you can elaborate particular properties where order should be maintained I will fix these specific areas

**Comment by pennyl67** [comment]
To be done – at some later point! No time now to look into the sorting until we end up with the final version of mappings!

BTW, do you harvest regularly the MetaShare repo?

Best,

penny
